# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deced99ead2b9a9a6766f8ba1021d367cb1366e44fab9000334a5776a2b88199b0916c7aca617fbdfcb6c843d76612f57d289c82d13b306e7f3505e0459003aa

test:
  secret_key_base: 33da77fc5345aafd0dda69a33110c75c7773f1456eec9d64efd2968afb36bffde9ec78d3b84fe18ecdeb70ff60457ea32df964432b4d6586ee3acb81a4c8c8bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
